from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('createguestorder/', views.createguestorder, name='createguestorder'),
    path('client/', views.client_dashboard, name='client_dashboard'),
    path('client/profile/update/', views.update_client_profile, name='update_client_profile'),
    path('client/orders/', views.order_tracking, name='order_tracking'),
    path('client/checkout/', views.checkout, name='checkout'),
    path('client/payment/<int:order_id>/', views.payment_placeholder, name='payment_placeholder'),
    path('api/cart/add/', views.api_cart_add, name='api_cart_add'),
    path('api/cart/update-quantity/', views.api_cart_update_quantity, name='api_cart_update_quantity'),
    path('api/cart/remove/', views.api_cart_remove, name='api_cart_remove'),
    path('api/cart/get/', views.api_cart_get, name='api_cart_get'),
    path('api/cart/import/', views.api_cart_import, name='api_cart_import'),
    path('guest/checkout/', views.guest_checkout, name='guest_checkout'),
    path('cart/add/dish/<int:dish_id>/', views.cart_add_dish, name='cart_add_dish'),
    path('cart/add/combo/<int:combo_id>/', views.cart_add_combo, name='cart_add_combo'),
    path('cart/update/', views.cart_update, name='cart_update'),
    path('cart/remove/<path:item_key>/', views.cart_remove, name='cart_remove'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/categories/', views.admin_categories, name='admin_categories'),
    path('admin/dishes/', views.admin_dishes, name='admin_dishes'),
    path('admin/dishes/new/', views.admin_dish_create, name='admin_dish_create'),
    path('admin/dishes/<int:dish_id>/edit/', views.admin_dish_edit, name='admin_dish_edit'),
    path('admin/dishes/<int:dish_id>/delete/', views.admin_dish_delete, name='admin_dish_delete'),
    path('admin/dishes/<int:dish_id>/data/', views.admin_dish_data, name='admin_dish_data'),
    path('admin/combos/', views.admin_combos, name='admin_combos'),
    path('admin/combos/new/', views.admin_combo_create, name='admin_combo_create'),
    path('admin/combos/<int:combo_id>/edit/', views.admin_combo_edit, name='admin_combo_edit'),
    path('admin/combos/<int:combo_id>/delete/', views.admin_combo_delete, name='admin_combo_delete'),
    path('admin/combos/<int:combo_id>/data/', views.admin_combo_data, name='admin_combo_data'),
    path('admin/offers/', views.admin_offers, name='admin_offers'),
    path('admin/offers/new/', views.admin_offer_create, name='admin_offer_create'),
    path('admin/offers/<int:offer_id>/edit/', views.admin_offer_edit, name='admin_offer_edit'),
    path('admin/offers/<int:offer_id>/delete/', views.admin_offer_delete, name='admin_offer_delete'),
    path('admin/orders/', views.admin_orders, name='admin_orders'),
    path('admin/orders/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/users/', views.admin_users, name='admin_users'),
]
