"""
Django settings for restowebsite project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8@k)mv5*d+$c@^wh5(h&6*pyh)^cjf($)k9-2#&7n(w+4-(-oc'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver', "grilladelegout.ma", "www.grilladelegout.ma"]


# Application definition

LOCAL_APPS = [
    'restaurant',
    'apps.core',
    'apps.accounts',
    'apps.catalog',
    'apps.cart',
    'apps.orders',
    'apps.payments',
    'apps.delivery',
    'apps.promotions',
    'apps.loyalty',
    'apps.referrals',
    'apps.notifications',
    'apps.analytics',
]

INSTALLED_APPS = [
    *LOCAL_APPS,
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restowebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CSRF_TRUSTED_ORIGINS = [
    "https://grilladelegout.ma",
    "https://www.grilladelegout.ma",
]
WSGI_APPLICATION = 'restowebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

USE_SQLITE = os.getenv('DEBUG') == 'True' or os.getenv('HOME') == '/home/aaliali'
# SQLite mode is treated as local/dev mode (runserver). Non-sqlite is waitress mode.
DEBUG = USE_SQLITE
print('USE_SQLITE', USE_SQLITE)
if USE_SQLITE:
    STATICFILES_DIRS = [
        BASE_DIR / "static",
    ]
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    STATIC_ROOT = BASE_DIR / 'static'

    #STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


    STATICFILES_DIRS = [
        BASE_DIR / "/static",
    ]
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mydb',        # Replace with your database name
            'USER': 'restouser',     # Replace with your database user
            'PASSWORD': os.getenv('PSQL_PASS'),  # Use environment variable for password
            'HOST': 'localhost',         # Or your database server address
            'PORT': '5432',              # Default PostgreSQL port
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'restaurant:dashboard'
LOGOUT_REDIRECT_URL = 'login'

THERMAL_PRINTER_ENABLED = os.getenv('THERMAL_PRINTER_ENABLED', 'true').lower() in ('1', 'true', 'yes')
THERMAL_PRINTER_NAME = os.getenv('THERMAL_PRINTER_NAME', 'XP-V330N')
